<h3><a name="Search API $[ja:メソッド]$[en:Methods]">Search API $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-Search-API-Method%3A-search">search</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#search(twitter4j.Query)">search()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Query.html">✔ pcs(via Query)</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-Search-API-Method%3A-trends">trends</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getTrends()">getTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-Search-API-Method%3A-trends-current">trends/current</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getCurrentTrends()">getCurrentTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-Search-API-Method%3A-trends-daily">trends/daily</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getDailyTrends()">getDailyTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-Search-API-Method%3A-trends-weekly">trends/weekly</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getWeeklyTrends()">getWeeklyTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Timeline $[ja:メソッド]$[en:Methods]">Timeline $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-public_timeline">statuses/public_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getPublicTimeline()">getPublicTimeline()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="">✔ s</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-home_timeline">statuses/home_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getHomeTimeline(twitter4j.Paging)">getHomeTimeline()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getHomeTimeline(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-friends_timeline">statuses/friends_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsTimeline()">getFriendsTimeline()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsTimeline(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-user_timeline">statuses/user_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserTimeline()">getUserTimeline()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserTimeline(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-mentions">statuses/mentions</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getMentions()">getMentions()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getMentions(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-retweeted_by_me">statuses/retweeted_by_me</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedByMe()">getRetweetedByMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedByMe(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-retweeted_to_me">statuses/retweeted_to_me</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedToMe()">getRetweetedToMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedToMe(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-retweets_of_me">statuses/retweets_of_me</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetsOfMe()">getRetweetsOfMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetsOfMe(twitter4j.Paging)">✔ smcp</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Status $[ja:メソッド]$[en:Methods]">Status $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses%C2%A0show">statuses/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showStatus(long)">showStatus()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses%C2%A0update">statuses/update</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateStatus(java.lang.String)">updateStatus()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses%C2%A0destroy">statuses/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyStatus(long)">destroyStatus()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-retweet">statuses/retweet</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#retweetStatus(long)">retweetStatus()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses-retweets">statuses/retweets</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweets(long)">getRetweets()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="User $[ja:メソッド]$[en:Methods]">User $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-users%C2%A0show">users/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showUser(java.lang.String)">showUser()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-users-search">users/search</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#searchUsers(java.lang.String,%20int)">searchUsers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#searchUsers(java.lang.String,%20int)">✔ p</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses%C2%A0friends">statuses/friends</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsStatuses()">getFriendsStatuses()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsStatuses(java.lang.String,%20twitter4j.Paging)">✔ C</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-statuses%C2%A0followers">statuses/followers</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersStatuses()">getFollowersStatuses()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersStatuses(twitter4j.Paging)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="List $[ja:メソッド]$[en:Methods]">List $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-POST-lists">user/lists (create)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createUserList(java.lang.String,%20boolean,%20java.lang.String)">createUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-POST-lists-id">user/lists/id (update)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateUserList(int,%20java.lang.String,%20boolean,%20java.lang.String)">updateUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-lists">user/lists (index)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserLists(java.lang.String,%20long)">getUserLists()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserLists(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-id">user/lists/id (show)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserLists(java.lang.String,%20long)">showUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-DELETE-list-id">user/lists/id (destroy)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyUserList(int)">destroyUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-statuses">user/lists/list_id/statuses</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListStatuses(java.lang.String,%20int,%20twitter4j.Paging)">getUserListStatuses()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListStatuses(java.lang.String,%20int,%20twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-memberships">user/lists/memberships</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMemberships(java.lang.String,%20long)">getUserListMemberships()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMemberships(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-subscriptions">user/lists/subscriptions</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscriptions(java.lang.String,%20long)">getUserListSubscriptions()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscriptions(java.lang.String,%20long)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="List Members $[ja:メソッド]$[en:Methods]">List Members $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-members">user/list_id/members (GET)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMembers(java.lang.String,%20int,%20long)">getUserListMembers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMembers(java.lang.String,%20int,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-POST-list-members">user/list_id/members (POST)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#addUserListMember(int,%20int)">addUserListMember()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-DELETE-list-members">user/list_id/members (DELETE)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#deleteUserListMember(int,%20int)">deleteUserListMember()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-members-id">user/list_id/members/id (GET list id)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#checkUserListMembership(java.lang.String,%20int,%20int)">checkUserListMembership()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="List Subscribers $[ja:メソッド]$[en:Methods]">List Subscribers $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-subscribers">user/list_id/subscribers (GET)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscribers(java.lang.String,%20int,%20long)">getUserListSubscribers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscribers(java.lang.String,%20int,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-POST-list-subscribers">user/list_id/subscribers (POST)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#subscribeUserList(java.lang.String,%20int)">subscribeUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-DELETE-list-subscribers">user/list_id/subscribers (DELETE)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#unsubscribeUserList(java.lang.String,%20int)">unsubscribeUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-GET-list-subscribers-id">user/list_id/subscribers/:id (GET list subscribers id)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#checkUserListSubscription(java.lang.String,%20int,%20int)">checkUserListSubscription()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Direct Message $[ja:メソッド]$[en:Methods]">Direct Message $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-direct_messages">direct_messages</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getDirectMessages()">getDirectMessages()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-direct_messages%C2%A0sent">direct_messages/sent</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSentDirectMessages()">getSentDirectMessages()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSentDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-direct_messages%C2%A0new">direct_messages/new</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#sendDirectMessage(java.lang.String,%20java.lang.String)">sendDirectMessage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-direct_messages%C2%A0destroy">direct_messages/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyDirectMessage(int)">destroyDirectMessage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Friendship $[ja:メソッド]$[en:Methods]">Friendship $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-friendships%C2%A0create">friendships/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createFriendship(java.lang.String)">createFriendship()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-friendships%C2%A0destroy">friendships/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyFriendship(java.lang.String)">destroyFriendship()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-friendships-exists">friendships/exists</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#existsFriendship(java.lang.String,%20java.lang.String)">existsFriendship()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-friendships-show">friendships/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showFriendship(int,%20int)">showFriendship()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Social Graph $[ja:メソッド]$[en:Methods]">Social Graph $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-friends%C2%A0ids">friends/ids</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsIDs()">getFriendsIDs()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsIDs(twitter4j.Paging)">✔ C</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-followers%C2%A0ids">followers/ids</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersIDs()">getFollowersIDs()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersIDs(twitter4j.Paging)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Account $[ja:メソッド]$[en:Methods]">Account $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0verify_credentials">account/verify_credentials</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#verifyCredentials()">verifyCredentials()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0rate_limit_status">account/rate_limit_status</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRateLimitStatus()">getRateLimitStatus()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0end_session">account/end_session</a></td><td><a href="http://groups.google.com/group/twitter4j/browse_thread/thread/5957722d596e269c/c2956d43a46b31b5?lnk=gst&q=stateless#c2956d43a46b31b5">$[ja:サポート予定なし]$[en:won't be supported]</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0update_delivery_device">account/update_delivery_device</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateDeliveryDevice(twitter4j.Device)">updateDelivelyDevice()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0update_profile_colors">account/update_profile_colors</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfileColors(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfileColors()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0update_profile_image">account/update_profile_image</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfileImage(java.io.File)">updateProfileImage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0update_profile_background_image">account/update_profile_background_image</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfileBackgroundImage(java.io.File,%20boolean)">updateProfileBackgroundImage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0update_profile">account/update_profile</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfile(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfile()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Favorite $[ja:メソッド]$[en:Methods]">Favorite $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-favorites">favorites</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFavorites()">getFavorites()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFavorites(int)">✔ p</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-favorites%C2%A0create">favorites/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createFavorite(long)">createFavorite() </a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-favorites%C2%A0destroy">favorites/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyFavorite(long)">destroyFavorite()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Notification $[ja:メソッド]$[en:Methods]">Notification $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-notifications%C2%A0follow">notifications/follow</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#enableNotification(java.lang.String)">enableNotification()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-notifications%C2%A0leave">notifications/leave</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#disableNotification(java.lang.String)">disableNotification()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Block $[ja:メソッド]$[en:Methods]">Block $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-blocks%C2%A0create">blocks/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createBlock(java.lang.String)">createBlock()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-blocks%C2%A0destroy">blocks/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyBlock(java.lang.String)">destroyBlock()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter+REST+API+Method%3A-blocks-exists">blocks/exists</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#existsBlock(java.lang.String)">existsBlock()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter+REST+API+Method%3A-blocks-blocking">blocks/blocking</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getBlockingUsers()">getBlockingUsers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getBlockingUsers(int)">✔ p</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-blocks-blocking-ids">blocks/ids</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getBlockingIDs()">getBlockingUsersIDs()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Spam Reporting $[ja:メソッド]$[en:Methods]">Spam Reporting $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-report_spam">report_spam</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#reportSpam(int)">reportSpam()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Saved Searches $[ja:メソッド]$[en:Methods]">Saved Searches $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-saved_searches">saves_searches</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSavedSearches()">getSavedSearches()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-saved_searches-show">saves_searches/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showSavedSearch(int)">showSavedSearch()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-saved_searches-create">saves_searches/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createSavedSearch(java.lang.String)">createSavedSearch()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-saved_searches-destroy">saves_searches/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroySavedSearch(int)">destroySavedSearch()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Local Trends $[ja:メソッド]$[en:Methods]">Local Trends $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-trends-available">trends/available</a></td><td><a href="http://twitter4j.org/jira/browse/TFJ-223">not yet supported(TFJ-233)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-trends-location">trends/</a></td><td><a href="http://twitter4j.org/jira/browse/TFJ-223">not yet supported(TFJ-233)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Help $[ja:メソッド]$[en:Methods]">Help $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-help%C2%A0test">help/test</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#test()">test()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor<h3><a name="Streaming API $[ja:メソッド]$[en:Methods]">Streaming API $[ja:メソッド]$[en:Methods]</a></h3><table class="api-matrix"><tr><th class="method-path">Twitter API $[ja:のパス]$[en:Path]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credential required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/filter">statuses/filter</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#filter(int,%20int[],%20java.lang.String[])">filter()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/filter">✔</a></td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/firehose">statuses/firehose</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#firehose(int)">firehose()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/retweet">statuses/retweet</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#retweet()">retweet()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/sample">statuses/sample</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#sample()">sample()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/sample">✔</a></td></tr>
</table>