<tag:h3 name="Search API $[ja:リソース]$[en:Resource]" title="Search API $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/search">search</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#search(twitter4j.Query)">search()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Query.html">✔ pcs(via Query)</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Trends $[ja:リソース]$[en:Resource]" title="Trends $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/trends">trends</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getTrends()">getTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/trends/current">trends/current</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getCurrentTrends()">getCurrentTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/trends/daily">trends/daily</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getDailyTrends()">getDailyTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/trends/weekly">trends/weekly</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getWeeklyTrends()">getWeeklyTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Timeline $[ja:リソース]$[en:Resource]" title="Timeline $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/public_timeline">statuses/public_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getPublicTimeline()">getPublicTimeline()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="">✔ s</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/home_timeline">statuses/home_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getHomeTimeline(twitter4j.Paging)">getHomeTimeline()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getHomeTimeline(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/friends_timeline">statuses/friends_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsTimeline()">getFriendsTimeline()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsTimeline(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/user_timeline">statuses/user_timeline</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserTimeline()">getUserTimeline()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserTimeline(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/mentions">statuses/mentions</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getMentions()">getMentions()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getMentions(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/retweeted_by_me">statuses/retweeted_by_me</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedByMe()">getRetweetedByMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedByMe(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/retweeted_to_me">statuses/retweeted_to_me</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedToMe()">getRetweetedToMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetedToMe(twitter4j.Paging)">✔ smcp</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Status $[ja:リソース]$[en:Resource]" title="Status $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/retweets_of_me">statuses/retweets_of_me</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetsOfMe()">getRetweetsOfMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweetsOfMe(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/show">statuses/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showStatus(long)">showStatus()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/statuses/update">statuses/update</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateStatus(java.lang.String)">updateStatus()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/statuses/destroy">statuses/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyStatus(long)">destroyStatus()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/statuses/retweet/:id">statuses/retweet</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#retweetStatus(long)">retweetStatus()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/retweets">statuses/retweets</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRetweets(long)">getRetweets()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/:id/retweeted_by">statuses/id/retweeted_by</a></td><td><a href="http://twitter4j.org/en/javadoc-latest/twitter4j/Twitter.html#getRetweetedBy(long)">* getRetweetedBy()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="">✔ cp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/:id/retweeted_by/ids">statuses/id/retweeted_by/ids</a></td><td><a href="http://twitter4j.org/en/javadoc-latest/twitter4j/Twitter.html#getRetweetedByIDs(long)">* getRetweetedByIds()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="">✔ cp</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="User $[ja:リソース]$[en:Resource]" title="User $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/users/show">users/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showUser(java.lang.String)">showUser()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/users/lookup">users/lookup</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#lookupUsers(int[])">lookupUsers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/users/search">users/search</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#searchUsers(java.lang.String,%20int)">searchUsers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#searchUsers(java.lang.String,%20int)">✔ p</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/users/suggestions">users/suggestions</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserSuggestions(java.lang.String)">getUserSuggestions()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/users/suggestions/slug">users/suggestions/category</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSuggestedUserCategories()">getSuggestedUserCategories() </a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/users/profile_image/:screen_name">users/profile_image/:screen_name.format</a></td><td><a href="http://twitter4j.org/jira/browse/TFJ-366">http://twitter4j.org/jira/browse/TFJ-366</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/friends">statuses/friends</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsStatuses()">getFriendsStatuses()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsStatuses(java.lang.String,%20twitter4j.Paging)">✔ C</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/statuses/followers">statuses/followers</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersStatuses()">getFollowersStatuses()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersStatuses(twitter4j.Paging)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="List $[ja:リソース]$[en:Resource]" title="List $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/:user/lists">user/lists (create)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createUserList(java.lang.String,%20boolean,%20java.lang.String)">createUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/:user/lists/:id">user/lists/id (update)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateUserList(int,%20java.lang.String,%20boolean,%20java.lang.String)">updateUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/lists">user/lists (index)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserLists(java.lang.String,%20long)">getUserLists()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserLists(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/lists/:id">user/lists/id (show)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserLists(java.lang.String,%20long)">showUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/delete/:user/lists/:id">user/lists/id (destroy)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyUserList(int)">destroyUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/lists/:id/statuses">user/lists/list_id/statuses</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListStatuses(java.lang.String,%20int,%20twitter4j.Paging)">getUserListStatuses()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListStatuses(java.lang.String,%20int,%20twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/lists/memberships">user/lists/memberships</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMemberships(java.lang.String,%20long)">getUserListMemberships()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMemberships(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/lists/subscriptions">user/lists/subscriptions</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscriptions(java.lang.String,%20long)">getUserListSubscriptions()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscriptions(java.lang.String,%20long)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="List Members $[ja:リソース]$[en:Resource]" title="List Members $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/:list_id/members">user/list_id/members (GET)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMembers(java.lang.String,%20int,%20long)">getUserListMembers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListMembers(java.lang.String,%20int,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/:user/:list_id/members">user/list_id/members (POST)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#addUserListMember(int,%20int)">addUserListMember()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/delete/:user/:id/members">user/list_id/members (DELETE)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#deleteUserListMember(int,%20int)">deleteUserListMember()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/:list_id/members/:id">user/list_id/members/id (GET list id)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#checkUserListMembership(java.lang.String,%20int,%20int)">checkUserListMembership()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="List Subscribers $[ja:リソース]$[en:Resource]" title="List Subscribers $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/:list_id/subscribers">user/list_id/subscribers (GET)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscribers(java.lang.String,%20int,%20long)">getUserListSubscribers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getUserListSubscribers(java.lang.String,%20int,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/:user/:list_id/subscribers">user/list_id/subscribers (POST)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#subscribeUserList(java.lang.String,%20int)">subscribeUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/delete/:user/:id/subscribers">user/list_id/subscribers (DELETE)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#unsubscribeUserList(java.lang.String,%20int)">unsubscribeUserList()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/:user/:list_id/subscribers/:id">user/list_id/subscribers/:id (GET list subscribers id)</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#checkUserListSubscription(java.lang.String,%20int,%20int)">checkUserListSubscription()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Direct Message $[ja:リソース]$[en:Resource]" title="Direct Message $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/direct_messages">direct_messages</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getDirectMessages()">getDirectMessages()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/direct_messages/sent">direct_messages/sent</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSentDirectMessages()">getSentDirectMessages()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSentDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/direct_messages/new">direct_messages/new</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#sendDirectMessage(java.lang.String,%20java.lang.String)">sendDirectMessage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/direct_messages/destroy">direct_messages/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyDirectMessage(int)">destroyDirectMessage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Friendship $[ja:リソース]$[en:Resource]" title="Friendship $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/friendships/create/:id">friendships/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createFriendship(java.lang.String)">createFriendship()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/friendships/destroy">friendships/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyFriendship(java.lang.String)">destroyFriendship()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/friendships/exists">friendships/exists</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#existsFriendship(java.lang.String,%20java.lang.String)">existsFriendship()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/friendships/show">friendships/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showFriendship(int,%20int)">showFriendship()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/friendships/incoming">friendships/incoming</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getIncomingFriendships(long)">getIncomingFriendships()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/friendships/outgoing">friendships/outgoing</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getOutgoingFriendships(long)">getOutgoingFriendships()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Friends and Followers $[ja:リソース]$[en:Resource]" title="Friends and Followers $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/friends/ids">friends/ids</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsIDs()">getFriendsIDs()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFriendsIDs(twitter4j.Paging)">✔ C</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/followers/ids">followers/ids</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersIDs()">getFollowersIDs()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFollowersIDs(twitter4j.Paging)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Account $[ja:リソース]$[en:Resource]" title="Account $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/account/verify_credentials">account/verify_credentials</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#verifyCredentials()">verifyCredentials()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/account/rate_limit_status">account/rate_limit_status</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getRateLimitStatus()">getRateLimitStatus()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/account/end_session">account/end_session</a></td><td><a href="http://groups.google.com/group/twitter4j/browse_thread/thread/5957722d596e269c/c2956d43a46b31b5?lnk=gst&q=stateless#c2956d43a46b31b5">$[ja:サポート予定なし]$[en:won't be supported]</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/account/update_delivery_device">account/update_delivery_device</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateDeliveryDevice(twitter4j.Device)">updateDelivelyDevice()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/account/update_profile_colors">account/update_profile_colors</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfileColors(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfileColors()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/account/update_profile_image">account/update_profile_image</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfileImage(java.io.File)">updateProfileImage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/account/update_profile_background_image">account/update_profile_background_image</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfileBackgroundImage(java.io.File,%20boolean)">updateProfileBackgroundImage()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/account/update_profile">account/update_profile</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#updateProfile(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfile()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Favorite $[ja:リソース]$[en:Resource]" title="Favorite $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/favorites">favorites</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFavorites()">getFavorites()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getFavorites(int)">✔ p</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/favorites/:id/create">favorites/:id/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createFavorite(long)">createFavorite() </a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/favorites/destroy">favorites/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyFavorite(long)">destroyFavorite()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Notification $[ja:リソース]$[en:Resource]" title="Notification $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/notifications/follow">notifications/follow</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#enableNotification(java.lang.String)">enableNotification()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/notifications/leave">notifications/leave</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#disableNotification(java.lang.String)">disableNotification()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Block $[ja:リソース]$[en:Resource]" title="Block $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/blocks/create">blocks/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createBlock(java.lang.String)">createBlock()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/blocks/destroy">blocks/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroyBlock(java.lang.String)">destroyBlock()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/blocks/exists">blocks/exists</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#existsBlock(java.lang.String)">existsBlock()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/blocks/blocking">blocks/blocking</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getBlockingUsers()">getBlockingUsers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getBlockingUsers(int)">✔ p</a></td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/blocks/blocking/ids">blocks/blocking/ids</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getBlockingUsersIDs()">getBlockingUsersIDs()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Spam Reporting $[ja:リソース]$[en:Resource]" title="Spam Reporting $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/report_spam">report_spam</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#reportSpam(int)">reportSpam()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Saved Searches $[ja:リソース]$[en:Resource]" title="Saved Searches $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/saved_searches">saves_searches</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getSavedSearches()">getSavedSearches()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/saved_searches/show">saves_searches/show</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#showSavedSearch(int)">showSavedSearch()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/saved_searches/create">saves_searches/create</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#createSavedSearch(java.lang.String)">createSavedSearch()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/post/saved_searches/destroy">saves_searches/destroy</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#destroySavedSearch(int)">destroySavedSearch()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Local Trends $[ja:リソース]$[en:Resource]" title="Local Trends $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/trends/available">trends/available</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getAvailableTrends()">getAvailableTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/trends/location/:woeid">trends/location/:woeid</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getLocationTrends(int)">getLocationTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Geo $[ja:リソース]$[en:Resource]" title="Geo $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/geo/reverse_geocode">geo/reverse_geocode</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#reverseGeoCode(twitter4j.GeoQuery)">reverseGeoCode()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/geo/id/:place_id">geo/id/:place_id</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#getGeoDetails(java.lang.String)">getGeoDetails()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Help $[ja:リソース]$[en:Resource]" title="Help $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="http://dev.twitter.com/doc/get/help/test">help/test</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/Twitter.html#test()">test()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Streaming API $[ja:メソッド]$[en:Methods]" title="Streaming API $[ja:メソッド]$[en:Methods]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resource]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]<br>(*: $[ja:最新ビルドのみ]$[en:latest build only])</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:一般に公開されている]$[en:Publicly Available]</th></tr>
<tr><td><a href="http://dev.twitter.com/pages/streaming_api_methods#statuses-filter">statuses/filter</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#filter(int,%20int[],%20java.lang.String[])">filter()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/filter">✔</a></td></tr>
<tr><td><a href="http://dev.twitter.com/pages/streaming_api_methods#statuses-firehose">statuses/firehose</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#firehose(int)">firehose()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/pages/streaming_api_methods#statuses-links">statuses/links</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#links(int)">links()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/links">✔</a></td></tr>
<tr><td><a href="http://dev.twitter.com/pages/streaming_api_methods#statuses-retweet">statuses/retweet</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#retweet()">retweet()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://dev.twitter.com/pages/streaming_api_methods#statuses-sample">statuses/sample</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#sample()">sample()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/sample">✔</a></td></tr>
</table></tag:h3>