<tag:h3 name="Timelines $[ja:リソース]$[en:Resources]" title="Timelines $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/mentions_timeline">statuses/mentions_timeline.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getMentionsTimeline()">getMentionsTimeline()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getMentionsTimeline(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/user_timeline">statuses/user_timeline.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getUserTimeline()">getUserTimeline()</a></td><td class="credential-rate-check">180</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getUserTimeline(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/home_timeline">statuses/home_timeline.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getHomeTimeline()">getHomeTimeline()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getHomeTimeline(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/retweets_of_me">statuses/retweets_of_me.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getRetweetsOfMe()">getRetweetsOfMe()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/TimelinesResources.html#getRetweetsOfMe(twitter4j.Paging)">✔ smc</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Tweets $[ja:リソース]$[en:Resources]" title="Tweets $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/retweets/:id">statuses/retweets/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#getRetweets(long)">getRetweets(statusId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/retweeters/ids">statuses/retweeters/ids.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#getRetweeterIds(long)">getRetweeterIds(statusId)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/show/:id">statuses/show/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#showStatus(long)">showStatus(statusId)</a></td><td class="credential-rate-check">180</td><td class="pagination"><a href="">4</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/statuses/destroy/:id">statuses/destroy/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#destroyStatus(long)">destroyStatus(statusId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/statuses/update">statuses/update.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#updateStatus(java.lang.String)">updateStatus(status)</a></td><td class="credential-rate-check">1000/day</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/statuses/retweet/:id">statuses/retweet/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#retweetStatus(long)">retweetStatus(statusId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/oembed">statuses/oembed.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#getOEmbed(twitter4j.OEmbedRequest)">getOEmbed(OEmbedRequest)</a></td><td class="credential-rate-check">180</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/statuses/update_with_media">statuses/update_with_media</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#updateStatus(java.lang.String)">updateStatus(status)</a></td><td class="credential-rate-check">1000/day</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/multiple-media-extended-entities">media/upload.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TweetsResources.html#uploadMedia(java.io.File)">uploadMedia()</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Search $[ja:リソース]$[en:Resource]" title="Search $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/search">search/tweets.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/SearchResource.html#search(twitter4j.Query)">search(query)</a></td><td class="credential-rate-check">180</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/SearchResource.html#search(twitter4j.Query)">✔ smc(via Query)</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Streaming $[ja:リソース]$[en:Resources]" title="Streaming $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:一般に公開されている]$[en:Publicly Available]</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/statuses/filter">statuses/filter.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/TwitterStream.html#filter(twitter4j.FilterQuery)">filter()</a></td><td class="credential-rate-check">N/A</td><td class="pagination"><a href="">✔</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/sample">statuses/sample.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/TwitterStream.html#sample()">sample()</a></td><td class="credential-rate-check">N/A</td><td class="pagination"><a href="">✔</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/firehose">statuses/firehose.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/TwitterStream.html#firehose(int)">firehose()</a></td><td class="credential-rate-check">N/A</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/statuses/user_timeline">statuses/user.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/TwitterStream.html#user()">user()</a></td><td class="credential-rate-check">N/A</td><td class="pagination"><a href="">✔</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/streaming-apis/streams/site">statuses/site.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/TwitterStream.html#site()">site()</a></td><td class="credential-rate-check">N/A</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Direct Message $[ja:リソース]$[en:Resources]" title="Direct Message $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/direct_messages">direct_messages.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#getDirectMessages()">getDirectMessages()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#getDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/direct_messages/sent">direct_messages/sent.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#getSentDirectMessages()">getSentDirectMessages()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#getSentDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/direct_messages/show">direct_messages/show/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#showDirectMessage(int)">showDirectMessage(directMessageId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/direct_messages/destroy/:id">direct_messages/destroy/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#destroyDirectMessage(long)">destroyDirectMessage(directMessageId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/direct_messages/new">direct_messages/new.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/DirectMessagesResources.html#sendDirectMessage(long,%20java.lang.String)">sendDirectMessage(userId, text)</a></td><td class="credential-rate-check">250/day</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Friends &amp; Followers $[ja:リソース]$[en:Resources]" title="Friends &amp; Followers $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/friends/ids">friends/ids.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFriendsIDs(long)">getFriendsIDs()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFriendsIDs(long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/followers/ids">followers/ids.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFollowersIDs(long)">getFollowersIDs()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFollowersIDs(long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/friendships/lookup">friendships/lookup.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#lookupFriendships(java.lang.String[])">lookupFriendships(userIds[])</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/friendships/incoming">friendships/incoming.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getIncomingFriendships(long)">getIncomingFriendships(cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/friendships/outgoing">friendships/outgoing.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getOutgoingFriendships(long)">getOutgoingFriendships(cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/friendships/create">friendships/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#createFriendship(long)">createFriendship(userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/friendships/destroy">friendships/destroy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#destroyFriendship(long)">destroyFriendship(userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/friendships/update">friendships/update.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#updateFriendship(long,%20boolean,%20boolean)">updateFriendship(userId,enableDeviceNotification,retweets)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/friendships/show">friendships/show.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#showFriendship(long,%20long)">showFriendship(sourceId, targetId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/friends/list">friends/list.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFriendsList(long,%20long)">getFriendsList(userId,cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFriendsList(long,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/followers/list">followers/list.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFollowersList(long,%20long)">getFollowersList(userId,cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/FriendsFollowersResources.html#getFollowersList(long,%20long)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Users $[ja:リソース]$[en:Resources]" title="Users $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/account/settings">account/settings.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getAccountSettings()">getAccuontSettings()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/account/verify_credentials">account/verify_credentials.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#verifyCredentials()">verifyCredentials()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/settings">account/settings.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#updateAccountSettings(java.lang.Integer,%20java.lang.Boolean,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateAccountSettings(trendLocationWoeid, sleepTimeEnabled, startSleepTime, endSleepTime, timeZone, lang)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/update_profile">account/update_profile.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#updateProfile(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfile(name, url, location, description)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/update_profile_background_image">account/update_profile_background_image.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#updateProfileBackgroundImage(java.io.File,%20boolean)">updateProfileBackgroundImage(file, tile)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/update_profile_colors">account/update_profile_colors.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#updateProfileColors(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfileColors(backgroundColor, textColor, linkColor, sidebarFillColor, sidebarBorderColor)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/update_profile_image">account/update_profile_image.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#updateProfileImage(java.io.File)">updateProfileImage(file)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/blocks/list">blocks/list.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getBlocksList()">getBlocksList()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getBlocksList(long)">✔ c</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/blocks/ids">blocks/ids.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getBlocksIDs()">getBlocksIDs()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/blocks/create">blocks/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#createBlock(long)">createBlock(userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/blocks/destroy">blocks/destroy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#destroyBlock(long)">destroyBlock(userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/lookup">users/lookup.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#lookupUsers(long[])">lookupUsers(userId[])</a></td><td class="credential-rate-check">180</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/show">users/show.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#showUser(long)">showUser(userId)</a></td><td class="credential-rate-check">180</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/search">users/search.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#searchUsers(java.lang.String,%20int)">searchUsers(query, page)</a></td><td class="credential-rate-check">180</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#searchUsers(java.lang.String,%20int)">✔ pc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/contributees">users/contributees.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getContributees(long)">getContributees(userId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/contributors">users/contributors.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getContributors(long)">getContributors(userId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/remove_profile_banner">account/remove_profile_banner</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#removeProfileBanner()">removeProfileBanner()</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/account/update_profile_banner">account/update_profile_banner</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#updateProfileBanner(java.io.File)">updateProfileBanner(image)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/mutes/users/create">mutes/users/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#createMute-long-">createMute(userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/mutes/users/destroy">mutes/users/destroy</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#destroyMute-long-">destroyMute(userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/mutes/users/ids">mutes/users/ids</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getMutesIDs-long-">getMutesIDs()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/mutes/users/list">mutes/users/list</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getMutesList-long-">getMutesList()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Suggested Users $[ja:リソース]$[en:Resources]" title="Suggested Users $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/suggestions/:slug">users/suggestions/:slug.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getUserSuggestions(java.lang.String)">getUserSuggestions(categorySlug)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/suggestions">users/suggestions.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getSuggestedUserCategories()">getSuggestedUserCategories()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/users/suggestions/%3Aslug/members">users/suggestions/:slug/members.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/UsersResources.html#getMemberSuggestions(java.lang.String)">getMemberSuggestions(categorySlug) </a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Favorites $[ja:リソース]$[en:Resources]" title="Favorites $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/favorites">favorites/list.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FavoritesResources.html#getFavorites()">getFavorites()</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/FavoritesResources.html#getFavorites(long,%20twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/favorites/destroy">favorites/destroy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FavoritesResources.html#destroyFavorite(long)">destroyFavorite(statusId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/favorites/create">favorites/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/FavoritesResources.html#createFavorite(long)">createFavorite(statusId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Lists $[ja:リソース]$[en:Resources]" title="Lists $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/list">lists/list.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserLists(long)">getUserLists(listOwnerUserId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/statuses">lists/statuses.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListStatuses(int,%20twitter4j.Paging)">getUserListStatuses(id, paging)</a></td><td class="credential-rate-check">180</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListStatuses(int,%20twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/members/destroy">lists/members/destroy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#destroyUserListMember(int,%20long)">destroyUserListMember(listId, userId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/memberships">lists/memberships.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListMemberships(java.lang.String,%20long)">getUserListMemberships(listMemberScreenName, cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListMemberships(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/subscribers">lists/subscribers.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListSubscribers(int,%20long)">getUserListSubscribers(listId, cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListSubscribers(int,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/subscribers/create">lists/subscribers/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#createUserListSubscription(int)">createUserListSubscription(listId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/subscribers/show">lists/subscribers/show.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#showUserListSubscription(int,%20long)">showUserListSubscription(listId, userId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/subscribers/destroy">lists/subscribers/destroy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#destroyUserListSubscription(int)">destroyUserListSubscription(listId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/members/create_all">lists/members/create_all.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#createUserListMembers(int,%20long[])">createUserListMembers(listId, userIDs[])</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/members/show">lists/members/show.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#showUserListMembership(int,%20long)">showUserListMembership(listId, userId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/members">lists/members.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListMembers(int,%20long)">getUserListMembers(listId, cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListMembers(int,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/members/create">lists/members/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#createUserListMember(int,%20long)">createUserListMember(listId, userId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/destroy">lists/destroy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#destroyUserList(int)">destroyUserList(listId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/update">lists/update.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#updateUserList(int,%20java.lang.String,%20boolean,%20java.lang.String)">updateUserList(listId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/lists/create">lists/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#createUserList(int)">createUserList(listId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/show">lists/show.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#showUserList(int)">showUserList(id)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/lists/subscriptions">lists/subscriptions.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListSubscriptions(long)">getUserListSubscriptions(cursor)</a></td><td class="credential-rate-check">15</td><td class="pagination"><a href="http://twitter4j.org/javadoc/twitter4j/api/ListsResources.html#getUserListSubscriptions(long)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Saved Searches $[ja:リソース]$[en:Resources]" title="Saved Searches $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/saved_searches/list">saved_searches/list.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/SavedSearchesResources.html#getSavedSearches()">getSavedSearches()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/saved_searches/show/%3Aid">saved_searches/show/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/SavedSearchesResources.html#showSavedSearch(int)">showSavedSearch(savedSearchId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/saved_searches/create">saved_searches/create.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/SavedSearchesResources.html#createSavedSearch(java.lang.String)">createSavedSearch(query)</a></td><td class="credential-rate-check">20lists/account</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/saved_searches/destroy/%3Aid">saved_searches/destroy/:id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/SavedSearchesResources.html#destroySavedSearch(int)">destroySavedSearch(savedSearchId)</a></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Places &amp; Geo $[ja:リソース]$[en:Resources]" title="Places &amp; Geo $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/geo/id/:place_id">geo/id/:place_id.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/PlacesGeoResources.html#getGeoDetails(java.lang.String)">getGeoDetails(placeId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/geo/reverse_geocode">geo/reverse_geocode.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/PlacesGeoResources.html#reverseGeoCode(twitter4j.GeoQuery)">reverseGeoCode(geoQuery)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/geo/search">geo/search.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/PlacesGeoResources.html#searchPlaces(twitter4j.GeoQuery)">searchPlaces(geoQuery)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/geo/similar_places">geo/similar_places.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/PlacesGeoResources.html#getSimilarPlaces(twitter4j.GeoLocation,%20java.lang.String,%20java.lang.String,%20java.lang.String)">getSimilarPlaces(location, name, containedWithin, streetAddress)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Trends $[ja:リソース]$[en:Resources]" title="Trends $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/trends/place">trends/place.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TrendsResources.html#getPlaceTrends(int)">getPlaceTrends()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/trends/available">trends/available.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TrendsResources.html#getAvailableTrends()">getAvailableTrends()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/trends/closest">trends/closest.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/TrendsResources.html#getClosestTrends(twitter4j.GeoLocation)">getClosestTrends()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Spam Reporting $[ja:リソース]$[en:Resource]" title="Spam Reporting $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/post/report_spam">report_spam.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/SpamReportingResource.html#reportSpam(long)">reportSpam(userId)</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Help $[ja:リソース]$[en:Resources]" title="Help $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:エンドポイント]$[en:Endpoint]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:レートリミット]$[en:Rate limit]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/help/configuration">help/configuration.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/HelpResources.html#getAPIConfiguration()">getAPIConfiguration()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/help/languages">help/languages.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/HelpResources.html#getLanguages()">getLanguages()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/help/privacy">help/privacy.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/HelpResources.html#getPrivacyPolicy()">getPrivacyPolicy()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/help/tos">help/tos.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/HelpResources.html#getTermsOfService()">getTermsOfService()</a></td><td class="credential-rate-check">15</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1.1/get/application/rate_limit_status">application/rate_limit_status.json</a></td><td><a href="http://twitter4j.org/javadoc/twitter4j/api/HelpResources.html#getRateLimitStatus()">getRateLimitStatus()</a></td><td class="credential-rate-check">180</td><td class="pagination">N/A</td></tr>
</table></tag:h3>