<tag:h3 name="Timeline $[ja:リソース]$[en:Resources]" title="Timeline $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/public_timeline">statuses/public_timeline.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getPublicTimeline()">getPublicTimeline()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/home_timeline">statuses/home_timeline.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getHomeTimeline()">getHomeTimeline()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getHomeTimeline(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/user_timeline">statuses/user_timeline.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getUserTimeline()">getUserTimeline()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getUserTimeline(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/mentions">statuses/mentions.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getMentions()">getMentions()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getMentions(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/retweeted_by_me">statuses/retweeted_by_me.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedByMe()">getRetweetedByMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedByMe(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/retweeted_to_me">statuses/retweeted_to_me.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedToMe()">getRetweetedToMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedToMe(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/retweets_of_me">statuses/retweets_of_me.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetsOfMe()">getRetweetsOfMe()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetsOfMe(twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="http://groups.google.com/group/twitter-development-talk/browse_thread/thread/cdc34ae78a2350b8">statuses/retweeted_to_user.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedToUser(java.lang.String,%20twitter4j.Paging)">getRetweetedToUser(userId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedToUser(java.lang.String,%20twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="http://groups.google.com/group/twitter-development-talk/browse_thread/thread/cdc34ae78a2350b8">statuses/retweeted_by_user.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedByUser(java.lang.String,%20twitter4j.Paging)">getRetweetedByUser(userId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TimelineMethods.html#getRetweetedByUser(java.lang.String,%20twitter4j.Paging)">✔ smc</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Tweets $[ja:リソース]$[en:Resources]" title="Tweets $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/show/:id">statuses/show/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#showStatus(long)">showStatus(statusId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/statuses/update">statuses/update.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#updateStatus(java.lang.String)">updateStatus(status)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/statuses/destroy/:id">statuses/destroy/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#destroyStatus(long)">destroyStatus(statusId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/statuses/retweet/:id">statuses/retweet/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#retweetStatus(long)">retweetStatus(statusId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/retweets/:id">statuses/retweets/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#getRetweets(long)">getRetweets(statusId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/:id/retweeted_by">statuses/:id/retweeted_by.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#getRetweetedBy(long)">getRetweetedBy(statusId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/:id/retweeted_by/ids">statuses/:id/retweeted_by/ids.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/StatusMethods.html#getRetweetedByIDs(long)">getRetweetedByIds(statusId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="User $[ja:リソース]$[en:Resources]" title="User $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/users/show">users/show.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#showUser(long)">showUser(userId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/users/lookup">users/lookup.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#lookupUsers(long[])">lookupUsers(userId[])</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/users/search">users/search.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#searchUsers(java.lang.String,%20int)">searchUsers(query, page)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#searchUsers(java.lang.String,%20int)">✔ p</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/users/suggestions">users/suggestions.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#getSuggestedUserCategories()">getSuggestedUserCategories()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/users/suggestions/:slug">users/suggestions/:slug.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#getUserSuggestions(java.lang.String)">getUserSuggestions(categorySlug)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://groups.google.com/group/twitter-development-talk/browse_thread/thread/cdc34ae78a2350b8">users/suggestions/:slug/members.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#getMemberSuggestions(java.lang.String)">getMemberSuggestions(categorySlug) </a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/users/profile_image/:screen_name">users/profile_image/:screen_name.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/UserMethods.html#getProfileImage(java.lang.String,%20twitter4j.ProfileImage.ImageSize)">getProfileImage(screenName, size)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Trends $[ja:リソース]$[en:Resources]" title="Trends $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/trends">trends.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TrendsMethods.html#getTrends()">getTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/trends/current">trends/current.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TrendsMethods.html#getCurrentTrends()">getCurrentTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/trends/daily">trends/daily.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TrendsMethods.html#getDailyTrends()">getDailyTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/trends/weekly">trends/weekly.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/TrendsMethods.html#getWeeklyTrends()">getWeeklyTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Local Trends $[ja:リソース]$[en:Resources]" title="Local Trends $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/trends/available">trends/available.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/LocalTrendsMethods.html#getAvailableTrends()">getAvailableTrends()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/trends/:woeid">trends/:woeid.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/LocalTrendsMethods.html#getLocationTrends(int)">getLocationTrends(woeid)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="List $[ja:リソース]$[en:Resources]" title="List $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/create">lists/create.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#createUserList(java.lang.String,%20boolean,%20java.lang.String)">createUserList(listName, isPublicList, description)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/update">lists/update.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#updateUserList(int,%20java.lang.String,%20boolean,%20java.lang.String)">updateUserList(listId, listName, isPublicList, description)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists">lists.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserLists(long)">getUserLists(cursor)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserLists(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/show">lists/show.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#showUserList(int)">showUserList(id)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/destroy">lists/destroy.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#destroyUserList(int)">destroyUserList(listId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/statuses">lists/statuses.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserListStatuses(int,%20twitter4j.Paging)">getUserListStatuses(id, paging)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserListStatuses(java.lang.String,%20int,%20twitter4j.Paging)">✔ smc</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/memberships">lists/memberships.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserListMemberships(java.lang.String,%20long)">getUserListMemberships(listMemberScreenName, cursor)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserListMemberships(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/subscriptions">lists/subscriptions.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserListSubscriptions(long)">getUserListSubscriptions(cursor)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getUserListSubscriptions(java.lang.String,%20long)">✔ C</a></td></tr>
<tr><td><a href="http://groups.google.com/group/twitter-development-talk/browse_thread/thread/cdc34ae78a2350b8">lists/all.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMethods.html#getAllUserLists(java.lang.String)">getAllUserLists(screenName)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="List Members $[ja:リソース]$[en:Resources]" title="List Members $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/members">lists/members.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMembersMethods.html#getUserListMembers(int,%20long)">getUserListMembers(listId, cursor)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMembersMethods.html#getUserListMembers(java.lang.String,%20int,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/members/create">lists/members/create.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMembersMethods.html#addUserListMember(int,%20long)">addUserListMember(listId, userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/members/create_all">lists/members/create_all.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMembersMethods.html#addUserListMembers(int,%20long[])">addUserListMembers(listId, userIDs[])</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/members/destroy">lists/members/destroy.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMembersMethods.html#deleteUserListMember(int,%20long)">deleteUserListMember(listId, userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/members/show">lists/members/show.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListMembersMethods.html#showUserListMembership(int,%20long)">showUserListMembership(listId, userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="List Subscribers $[ja:リソース]$[en:Resources]" title="List Subscribers $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/subscribers">lists/subscribers.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListSubscribersMethods.html#getUserListSubscribers(int,%20long)">getUserListSubscribers(listId, cursor)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListSubscribersMethods.html#getUserListSubscribers(java.lang.String,%20int,%20long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/subscribers/create">lists/subscribers/create.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListSubscribersMethods.html#createUserListSubscription(int)">createUserListSubscription(listId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/lists/subscribers/destroy">lists/subscribers/destroy.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListSubscribersMethods.html#destroyUserListSubscription(int)">destroyUserListSubscription(listId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/lists/subscribers/show">lists/subscribers/show.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/ListSubscribersMethods.html#showUserListSubscription(int,%20long)">showUserListSubscription(listId, userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Direct Message $[ja:リソース]$[en:Resources]" title="Direct Message $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/direct_messages">direct_messages.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#getDirectMessages()">getDirectMessages()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#getDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/direct_messages/sent">direct_messages/sent.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#getSentDirectMessages()">getSentDirectMessages()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#getSentDirectMessages(twitter4j.Paging)">✔ smcp</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/direct_messages/new">direct_messages/new.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#sendDirectMessage(long,%20java.lang.String)">sendDirectMessage(userId, text)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/direct_messages/destroy/:id">direct_messages/destroy/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#destroyDirectMessage(long)">destroyDirectMessage(directMessageId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://groups.google.com/group/twitter-development-talk/browse_thread/thread/cdc34ae78a2350b8">direct_messages/show/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/DirectMessageMethods.html#showDirectMessage(int)">showDirectMessage(directMessageId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Friendship $[ja:リソース]$[en:Resources]" title="Friendship $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/friendships/create">friendships/create.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#createFriendship(long)">createFriendship(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/friendships/destroy">friendships/destroy.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#destroyFriendship(long)">destroyFriendship(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/friendships/exists">friendships/exists.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#existsFriendship(java.lang.String,%20java.lang.String)">existsFriendship(userA, userB)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/friendships/show">friendships/show.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#showFriendship(long,%20long)">showFriendship(sourceId, targetId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/friendships/incoming">friendships/incoming.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#getIncomingFriendships(long)">getIncomingFriendships(cursor)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/friendships/outgoing">friendships/outgoing.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#getOutgoingFriendships(long)">getOutgoingFriendships(cursor)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="http://groups.google.com/group/twitter-development-talk/browse_thread/thread/cdc34ae78a2350b8">friendships/lookup.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendshipMethods.html#lookupFriendships(java.lang.String[])">lookupFriendships(userIds[])</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Friends and Followers $[ja:リソース]$[en:Resources]" title="Friends and Followers $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/friends/ids">friends/ids.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendsFollowersMethods.html#getFriendsIDs(long)">getFriendsIDs()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendsFollowersMethods.html#getFriendsIDs(long)">✔ C</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/followers/ids">followers/ids.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendsFollowersMethods.html#getFollowersIDs(long)">getFollowersIDs()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FriendsFollowersMethods.html#getFollowersIDs(long)">✔ C</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Account $[ja:リソース]$[en:Resources]" title="Account $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/account/verify_credentials">account/verify_credentials.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#verifyCredentials()">verifyCredentials()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/account/rate_limit_status">account/rate_limit_status.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#getRateLimitStatus()">getRateLimitStatus()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/account/totals">account/totals.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#getAccountTotals()">getAccountTotals()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/account/settings">account/settings.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#getAccountSettings()">getAccuontSettings()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/account/settings">account/settings.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#updateAccountSettings(java.lang.Integer,%20java.lang.Boolean,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateAccountSettings(trendLocationWoeid, sleepTimeEnabled, startSleepTime, endSleepTime, timeZone, lang)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/account/update_profile_colors">account/update_profile_colors.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#updateProfileColors(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfileColors(backgroundColor, textColor, linkColor, sidebarFillColor, sidebarBorderColor)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/account/update_profile_image">account/update_profile_image.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#updateProfileImage(java.io.File)">updateProfileImage(file)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/account/update_profile_background_image">account/update_profile_background_image.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#updateProfileBackgroundImage(java.io.File,%20boolean)">updateProfileBackgroundImage(file, tile)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/account/update_profile">account/update_profile.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/AccountMethods.html#updateProfile(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)">updateProfile(name, url, location, description)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Favorite $[ja:リソース]$[en:Resources]" title="Favorite $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/favorites">favorites.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FavoriteMethods.html#getFavorites()">getFavorites()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FavoriteMethods.html#getFavorites(int)">✔ p</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/favorites/create/:id">favorites/create/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FavoriteMethods.html#createFavorite(long)">createFavorite(statusId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/favorites/destroy/:id">favorites/destroy/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/FavoriteMethods.html#destroyFavorite(long)">destroyFavorite(statusId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Notification $[ja:リソース]$[en:Resources]" title="Notification $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/notifications/follow">notifications/follow.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/NotificationMethods.html#enableNotification(long)">enableNotification(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/notifications/leave">notifications/leave.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/NotificationMethods.html#disableNotification(long)">disableNotification(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Block $[ja:リソース]$[en:Resources]" title="Block $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/blocks/create">blocks/create.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/BlockMethods.html#createBlock(long)">createBlock(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/blocks/destroy">blocks/destroy.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/BlockMethods.html#destroyBlock(long)">destroyBlock(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/blocks/exists">blocks/exists.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/BlockMethods.html#existsBlock(long)">existsBlock(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/blocks/blocking">blocks/blocking.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/BlockMethods.html#getBlockingUsers()">getBlockingUsers()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/api/BlockMethods.html#getBlockingUsers(int)">✔ p</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/blocks/blocking/ids">blocks/blocking/ids.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/BlockMethods.html#getBlockingUsersIDs()">getBlockingUsersIDs()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Spam Reporting $[ja:リソース]$[en:Resources]" title="Spam Reporting $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/report_spam">report_spam.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/SpamReportingMethods.html#reportSpam(long)">reportSpam(userId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Saved Searches $[ja:リソース]$[en:Resources]" title="Saved Searches $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/saved_searches">saved_searches.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/SavedSearchesMethods.html#getSavedSearches()">getSavedSearches()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/saved_searches/show/:id">saved_searches/show/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/SavedSearchesMethods.html#showSavedSearch(int)">showSavedSearch(savedSearchId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/saved_searches/create">saved_searches/create.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/SavedSearchesMethods.html#createSavedSearch(java.lang.String)">createSavedSearch(query)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/saved_searches/destroy/:id">saved_searches/destroy/:id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/SavedSearchesMethods.html#destroySavedSearch(int)">destroySavedSearch(savedSearchId)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Geo $[ja:リソース]$[en:Resources]" title="Geo $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/geo/search">geo/search.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/GeoMethods.html#searchPlaces(twitter4j.GeoQuery)">searchPlaces(geoQuery)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/geo/similar_places">geo/similar_places.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/GeoMethods.html#getSimilarPlaces(twitter4j.GeoLocation,%20java.lang.String,%20java.lang.String,%20java.lang.String)">getSimilarPlaces(location, name, containedWithin, streetAddress)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/geo/reverse_geocode">geo/reverse_geocode.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/GeoMethods.html#reverseGeoCode(twitter4j.GeoQuery)">reverseGeoCode(geoQuery)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/geo/id/:place_id">geo/id/:place_id.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/GeoMethods.html#getGeoDetails(java.lang.String)">getGeoDetails(placeId)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/geo/place">geo/place.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/GeoMethods.html#createPlace(java.lang.String,%20java.lang.String,%20java.lang.String,%20twitter4j.GeoLocation,%20java.lang.String)">createPlace(name, containedWithin, token, location, streetAddress)</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Legal $[ja:リソース]$[en:Resources]" title="Legal $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/legal/tos">legal/tos.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/LegalResources.html#getTermsOfService()">getTermsOfService()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/legal/privacy">legal/privacy.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/LegalResources.html#getPrivacyPolicy()">getPrivacyPolicy()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Help $[ja:リソース]$[en:Resource]" title="Help $[ja:リソース]$[en:Resource]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/help/test">help/test.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/HelpMethods.html#test()">test()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/help/configuration">help/configuration.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/HelpMethods.html#getAPIConfiguration()">getAPIConfiguration()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/help/languages">help/languages.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/HelpMethods.html#getLanguages()">getLanguages()</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination">N/A</td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Streamed Tweets $[ja:リソース]$[en:Resources]" title="Streamed Tweets $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:一般に公開されている]$[en:Publicly Available]</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/post/statuses/filter">statuses/filter.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#filter(twitter4j.FilterQuery)">filter()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/filter">✔</a></td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/firehose">statuses/firehose.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#firehose(int)">firehose()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/links">statuses/links.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#links(int)">links()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/retweet">statuses/retweet.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#retweet()">retweet()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination">N/A</td></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/statuses/sample">statuses/sample.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/TwitterStream.html#sample()">sample()</a></td><td class="credential-rate-check">✔</td><td class="credential-rate-check"></td><td class="pagination"><a href="http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/sample">✔</a></td></tr>
</table>* s: since_id, m: max_id, c: count,  p: page, C:cursor</tag:h3><tag:h3 name="Search API $[ja:リソース]$[en:Resources]" title="Search API $[ja:リソース]$[en:Resources]"><table class="api-matrix"><tr><th class="method-path">$[ja:リソース]$[en:Resources]</th><th class="t4jmethod">Twitter4J $[ja:のメソッド]$[en:Method]</th><th class="credential-rate">$[ja:要認証]$[en:Credentials required]</th><th class="credential-rate">$[ja:Rate リミット]$[en:Rate limited]</th><th class="paging-support">$[ja:ページングサポート]$[en:Pagination](*)</th></tr>
<tr><td><a href="https://dev.twitter.com/docs/api/1/get/search">search.json</a></td><td><a href="http://twitter4j.org/en/javadoc/twitter4j/api/SearchMethods.html#search(twitter4j.Query)">search(query)</a></td><td class="credential-rate-check"></td><td class="credential-rate-check">✔</td><td class="pagination"><a href="http://twitter4j.org/en/javadoc/twitter4j/Query.html">✔ pcs(via Query)</a></td></tr>
</table></tag:h3>